=== daxplore/daxplore-presenter/src/org/daxplore/shared/UploadFileManifest.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="daxploreUploadFileManifest">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="fileVersion" type="fileVersionType" />
				<xsd:element name="supportedLocales" type="supportedLocaleType" />
				<xsd:element name="defaultLocale" type="defaultLocaleType" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="fileVersionType">
		<xsd:sequence>
			<xsd:element name="major" type="xsd:nonNegativeInteger"></xsd:element>
			<xsd:element name="minor" type="xsd:nonNegativeInteger"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="language-BCP47-Type">
		<xsd:restriction base="xsd:language" />
	</xsd:simpleType>

	<xsd:complexType name="supportedLocaleType">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="language-BCP47" type="language-BCP47-Type" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="defaultLocaleType">
		<xsd:sequence>
			<xsd:element name="language-BCP47" type="language-BCP47-Type" />
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== daxplore/daxplore-presenter/test/org/daxplore/presenter/server/upload/manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<daxploreUploadFileManifest
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="UploadFileManifest.xsd">
	<fileVersion>
		<major>9</major>
		<minor>32</minor>
	</fileVersion>
	<supportedLocales>
		<language-BCP47>en</language-BCP47>
		<language-BCP47>sv</language-BCP47>
	</supportedLocales>
	<defaultLocale>
		<language-BCP47>en</language-BCP47>
	</defaultLocale>
</daxploreUploadFileManifest>
